services:
  web:
    build: .
    image: innakitchen:dev
    container_name: innakitchen-web
    ports:
      - "8080:80"
    restart: unless-stopped

  cypress:
    image: cypress/included:13.13.2
    container_name: innakitchen-cypress
    working_dir: /e2e
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web
    volumes:
      - ./:/e2e
    command: ["run", "--browser", "electron"]
