name: CI/CD for innakitchen

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/innakitchen
  DOCKER_PLATFORMS: linux/amd64

jobs:
  test:
    name: E2E (Cypress)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # สร้างอิมเมจ dev สำหรับ service web ใน docker-compose.yml
      - name: Build image (dev)
        run: docker build -t innakitchen:dev .

      # รัน web ผ่าน Docker Compose (เลี่ยงชื่อชน)
      - name: Start web via Compose
        run: docker compose up -d web

      - name: Wait for web (up to 30s)
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:8080 > /dev/null; then
              echo "Web is up"
              exit 0
            fi
            sleep 1
          done
          echo "Web did not become ready in time" >&2
          docker compose logs web || true
          exit 1

      # รัน Cypress ผ่าน service cypress ใน compose
      - name: Run Cypress via Docker Compose
        run: docker compose run --rm cypress

      - name: Print logs (always)
        if: always()
        run: docker compose logs --no-color || true

      - name: Tear down (always)
        if: always()
        run: docker compose down -v

  build_and_push:
    name: Build & Push GHCR
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ใช้ GITHUB_TOKEN สำหรับ push ไป GHCR (ต้องมี packages: write)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Mac mini
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Mac mini and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.COMPOSE_PROJECT_DIR }}
            # สำหรับฝั่ง Mac mini ให้ใช้ PAT ที่มีอย่างน้อย read:packages
            docker login ghcr.io -u "${{ github.repository_owner }}" -p "${{ secrets.GHCR_READ_TOKEN }}"
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f
